### ISSUE TITLE
[新功能请求]添加自定义字体选项

### ISSUE THREAD

**Issue by a15355447898a** [Richasy/ReaderCopilot.Public#1]
在"rss追踪"中有这个选项,新的软件这个功能没了,请添加回来
一个好看的字体可以增加阅读的舒适性

**Comment by Richasy** [comment]
这个目前的优先级不高...
应用会优先保持和第一方应用类似的设计与体验，但如果有相同诉求的人较多，可以在未来考虑实现

**Comment by larachung** [comment]
> 这个目前的优先级不高... 应用会优先保持和第一方应用类似的设计与体验，但如果有相同诉求的人较多，可以在未来考虑实现

部分 ePub 為了保證閱讀體驗，會在 CSS 中指定正文字型，甚至在 ePub 文件內部嵌入字型文件。而當閱讀器缺少此項支援時，會在一定程度上破壞閱體驗。閱讀助理似乎並不支援在 CSS 中指定普通的字型族名，而只技援通用字型族名，這便會造成一個十分嚴重的後果——在 CSS 列表末尾加入了襯線體的通用字型族名的 ePub（形如```font-family: "某字型", serif;```）會使用醜陋的中易宋体或新細明體。考慮到這兩款字型有多麼「臭名昭著」，這對閱讀體驗有極大的破壞。

希望可以考慮在未來完善 ePub 閱讀器對 CSS 指定字型和內嵌字型的支援，謝謝！

**Comment by Richasy** [comment]
> > 这个目前的优先级不高... 应用会优先保持和第一方应用类似的设计与体验，但如果有相同诉求的人较多，可以在未来考虑实现
> 
> 部分 ePub 為了保證閱讀體驗，會在 CSS 中指定正文字型，甚至在 ePub 文件內部嵌入字型文件。而當閱讀器缺少此項支援時，會在一定程度上破壞閱體驗。閱讀助理似乎並不支援在 CSS 中指定普通的字型族名，而只技援通用字型族名，這便會造成一個十分嚴重的後果——在 CSS 列表末尾加入了襯線體的通用字型族名的 ePub（形如`font-family: "某字型", serif;`）會使用醜陋的中易宋体或新細明體。考慮到這兩款字型有多麼「臭名昭著」，這對閱讀體驗有極大的破壞。
> 
> 希望可以考慮在未來完善 ePub 閱讀器對 CSS 指定字型和內嵌字型的支援，謝謝！

不确定 [自定义阅读体验](https://readercopilot.richasy.com/docs/custom-reader#%E9%99%84%E5%8A%A0%E6%A0%B7%E5%BC%8F) 这一块是否可以解决你的问题，阅读助理支持注入css

**Comment by larachung** [comment]
> > > 这个目前的优先级不高... 应用会优先保持和第一方应用类似的设计与体验，但如果有相同诉求的人较多，可以在未来考虑实现
> > 
> > 
> > 部分 ePub 為了保證閱讀體驗，會在 CSS 中指定正文字型，甚至在 ePub 文件內部嵌入字型文件。而當閱讀器缺少此項支援時，會在一定程度上破壞閱體驗。閱讀助理似乎並不支援在 CSS 中指定普通的字型族名，而只技援通用字型族名，這便會造成一個十分嚴重的後果——在 CSS 列表末尾加入了襯線體的通用字型族名的 ePub（形如`font-family: "某字型", serif;`）會使用醜陋的中易宋体或新細明體。考慮到這兩款字型有多麼「臭名昭著」，這對閱讀體驗有極大的破壞。
> > 希望可以考慮在未來完善 ePub 閱讀器對 CSS 指定字型和內嵌字型的支援，謝謝！
> 
> 不确定 [自定义阅读体验](https://readercopilot.richasy.com/docs/custom-reader#%E9%99%84%E5%8A%A0%E6%A0%B7%E5%BC%8F) 这一块是否可以解决你的问题，阅读助理支持注入css

感謝回應，嘗試了一下這種方法，可以解決部分問題。但會帶來新的問題，例如簡體中文、繁體中文和日語的漢字字形各不相同，所以十分需要針對不同語言設定不同字型，而用注入 CSS 的單一字型覆蓋掉設定，難以滿足這個需求。而且依舊無法滿足一些 ePub 嵌入字型文件來訂製標題甚至正文樣式的情況，例如內嵌了一個藝術字字型来訂製章節標題卻只能根據 CSS 行末的通用字型族顯示為普通的微軟雅黑/微軟正黑體或中易宋體/新細明體；又或是作者將一本古典文學書籍的正文字型設定為了傳統字形字型來契合作品風格，卻只能根據 CSS 行末的通用字型族顯示為 Windows 的幾款預裝字型或被注入的 CSS 覆蓋掉。

所以還是十分希望在未來完善這方面的支援，感謝！

**Comment by Richasy** [comment]
是否有实现你需求的应用？这可以帮助我更好地理解你所预期的效果

**Comment by larachung** [comment]
> 是否有实现你需求的应用？这可以帮助我更好地理解你所预期的效果

[calibre](https://calibre-ebook.com/) 的 veiwer，例如當 ePub 內部的 CSS 有 ```p {font-family: "Source Han Serif", serif;}``` 時，便可在無 CSS 注入覆蓋時，令 ```<p>``` 元素的字型顯示為思源宋體，若系統無思源宋體則根據後面的```serif```回落到系統默認的襯線體。

又或者我會為了訂製標題樣式，在 ePub 文件中嵌入 Source Serif 4 的字型文件，並在 ePub 文件內部的 CSS 中添加：
```
@font-face {
   font-family: "Source Serif 4 Display";
   src: url('../font/SourceSerif4Display-Regular.otf') format('OpenType');
}

h1 {
   font-family: "Source Serif 4 Display";
}
```
便可在無 CSS 注入覆蓋時，正常調用嵌入的字型，並令 ```<h1>``` 元素的字型顯示為 CSS 所指定的 Source Serif。

[這是一個簡單的示例文件](https://github.com/Richasy/ReaderCopilot.Public/files/13805248/sample.zip)可供您測試使用，由於 github 無法上傳 ePub 我便將後綴名更改為了 .zip，您可以改為 ePub 以供閱讀，也可以直接解壓縮來查看內部的文件。它只有一頁內容，其中正文在文件內部的 CSS 中被設定為了思源宋體（如果您的系統中沒有安裝思源宋體，便會根據後面的 ```serif``` 回落到系統默認的襯線體）；標題在文件內部的 CSS 中被設定為了內嵌的 Source Serif 4 Display，以對應 CSS 指定系統安裝的字型和 CSS 指定嵌入 ePub 的字型兩種情況。

**Comment by Richasy** [comment]
> > 是否有实现你需求的应用？这可以帮助我更好地理解你所预期的效果
> 
> [calibre](https://calibre-ebook.com/) 的 veiwer，例如當 ePub 內部的 CSS 有 `p {font-family: "Source Han Serif", serif;}` 時，便可在無 CSS 注入覆蓋時，令 `<p>` 元素的字型顯示為思源宋體，若系統無思源宋體則根據後面的`serif`回落到系統默認的襯線體。
> 
> 又或者我會為了訂製標題樣式，在 ePub 文件中嵌入 Source Serif 4 的字型文件，並在 ePub 文件內部的 CSS 中添加：
> 
> ```
> @font-face {
>    font-family: "Source Serif 4 Display";
>    src: url('../font/SourceSerif4Display-Regular.otf') format('OpenType');
> }
> 
> h1 {
>    font-family: "Source Serif 4 Display";
> }
> ```
> 
> 便可在無 CSS 注入覆蓋時，正常調用嵌入的字型，並令 `<h1>` 元素的字型顯示為 CSS 所指定的 Source Serif。
> 
> [這是一個簡單的示例文件](https://github.com/Richasy/ReaderCopilot.Public/files/13805248/sample.zip)可供您測試使用，由於 github 無法上傳 ePub 我便將後綴名更改為了 .zip，您可以改為 ePub 以供閱讀，也可以直接解壓縮來查看內部的文件。它只有一頁內容，其中正文在文件內部的 CSS 中被設定為了思源宋體（如果您的系統中沒有安裝思源宋體，便會根據後面的 `serif` 回落到系統默認的襯線體）；標題在文件內部的 CSS 中被設定為了內嵌的 Source Serif 4 Display，以對應 CSS 指定系統安裝的字型和 CSS 指定嵌入 ePub 的字型兩種情況。

Hi，新的版本（v2.2412.13.0）也许可以解决这个问题， 默认情况下不会覆盖电子书指定的字体，这两天就会过审发布，届时可以更新一下看看
