### ISSUE TITLE
[新功能请求] 希望播客的列表增加按照时间正序排列

### ISSUE THREAD

**Issue by Dagwbl** [Richasy/ReaderCopilot.Public#10]
幻哥，你好啊！

如题，有时候新发现一个好的博客，一个节目分成好几个博客，默认的时间逆序自动播放的时候顺序就不大一样了。

希望增加能够按照**时间从旧到新的顺序**排列。

**Comment by Richasy** [comment]
此问题已修复，请更新至新版本（1.2310.2.0）

**Comment by Dagwbl** [comment]
刚刚还在听博客，手机就收到更新的消息，太棒啦，爱你❤️
