### ISSUE TITLE
[Bug] 无法使用 RSS 服务中的 Google Reader 登录 the old reader

### ISSUE THREAD

**Issue by leechaojie** [Richasy/ReaderCopilot.Public#11]
测试: 使用其他第三方的客户端通过 Google Reader API 可以登录 [The Old Reader](https://theoldreader.com/)
排除了网络问题；

服务器一栏填写的是 https://theoldreader.com/ ，用户名密码填写的就是 The Old Reader 的用户名密码。提示 **_尝试连接服务时失败，请检查网络或者所填信息是否准确_**

**Comment by Richasy** [comment]
此问题已修复，请更新至新版本（1.2310.2.0）
