### ISSUE TITLE
[新功能请求]书架增加OPDS（开放式出版发布系统）协议支持

### ISSUE THREAD

**Issue by mwnu** [Richasy/ReaderCopilot.Public#12]
开放式出版发布系统 (OPDS) 目录格式是一种基于 Atom 和 HTTP协定的电子出版品同步格式。OPDS 目录支援电子出版品的聚合、分发、发现和取得。OPDS 目录使用现有或新兴的开放标准和约定，优先考虑简单性。
——以上来自[维基百科](https://zh.wikipedia.org/zh-cn/%E9%96%8B%E6%94%BE%E5%BC%8F%E5%87%BA%E7%89%88%E7%99%BC%E4%BD%88%E7%B3%BB%E7%B5%B1)

常见的书库服务如Calibre和电子书阅读器如Moon+都支持OPDS，就像RSS中的Fever、Google Reader那样，直接从服务器的API同步和下载书籍，无需再本地在创建书库导入文档文件。

**Comment by Richasy** [comment]
我这段时间了解了一下 OPDS，这是一个不错的思路，但是和目前应用的数据存储架构不太兼容。应用会单独存储每一本书，而不是以订阅的形式读取，未来会考虑是否可以通过插件或者其它的方式来间接支持，但目前不是优先事项
