### ISSUE TITLE
尝试连接到小幻助理失败 AppUnavailable

### ISSUE THREAD

**Issue by wuhuaqing6668** [Richasy/ReaderCopilot.Public#14]
阅读助理1.2310.1.0
小幻助理1.2309.2.0
![Snipaste_2023-10-08_18-10-18](https://github.com/Richasy/ReaderCopilot.Public/assets/131956300/50aaa0e7-bae9-41f3-b5ab-5e917cdbe9ca)

**Comment by Richasy** [comment]
它有时候确实不太稳定，后台查看发生概率大概是百分之一。
可以尝试重启设备或者重新安装小幻助理，或者等一会儿再试

**Comment by wuhuaqing6668** [comment]
全部重新安装过，也重启过 都没有成功过，WIN11也更新了

**Comment by wuhuaqing6668** [comment]
![image](https://github.com/Richasy/ReaderCopilot.Public/assets/131956300/60fa329b-ce5a-4c32-a1d9-05c3ac359c85)

**Comment by Richasy** [comment]
我会在下次更新中加一个选项，以允许使用协议启动来处理，预计是下周末更新

**Comment by wuhuaqing6668** [comment]
已更新版本问题依在
![image](https://github.com/Richasy/ReaderCopilot.Public/assets/131956300/dacda1db-0ba9-4e7a-9c72-8b6a5d7064c8)

**Comment by wuhuaqing6668** [comment]
安装dotnet-sdk-7.0.401-win-x64后可以使用。

**Comment by Richasy** [comment]
OK，感谢提供这个信息，那我先关闭这个问题了
