### ISSUE TITLE
epub显示不完全

### ISSUE THREAD

**Issue by SalicylicAcid** [Richasy/ReaderCopilot.Public#16]
![image](https://github.com/Richasy/ReaderCopilot.Public/assets/37034452/bc753270-565e-41a6-8958-32f749fbda7b)
书本：
[《狂飙》朱俊懿 徐纪周.zip](https://github.com/Richasy/ReaderCopilot.Public/files/12842363/default.zip)

**Comment by Richasy** [comment]
这个是该 epub 的特殊样式导致的。
请按如下步骤操作：

1. 打开该书
2. 点击阅读器中间区域调出顶部菜单。
3. 依次打开 `设置` -> `阅读器颜色设置` -> `附加样式`，选择在默认编辑器中打开（阅读器会有一个对话框，先不要关闭）

在编辑器中使用下面的代码覆盖默认的样式：

```json
{
    "a": {
        "color": "#eeeeee"
    },
    "html": {
        "margin": "0"
    },
    "body": {
        "margin": "0"
    }
}
```

保存后，返回阅读器，点击对话框的 `确认` 按钮，阅读就正常了
