### ISSUE TITLE
[错误]"阅读列表"栏无法使用触控滚动界面

### ISSUE THREAD

**Issue by a15355447898a** [Richasy/ReaderCopilot.Public#19]
https://github.com/Richasy/ReaderCopilot.Public/assets/62456287/a11052b2-da13-425a-8552-c716bb5c43f1

系统:Windows11
设备:surface go2
应用版本:最新

**Comment by Richasy** [comment]
这个看上去有点奇怪，我用手头的 Surface Pro 7+ 和 Surface Book 进行了测试，均可以正常滚动。

所以这个问题暂时无法复现，我会在这两天更新一下版本，你可以在那之后更新下看看

**Comment by Richasy** [comment]
暂时关闭该问题，因为无法复现。如果你对此有疑问，可以随时再打开它
