### ISSUE TITLE
[新功能请求]inoreader,可以仅通过登录来同步信息

### ISSUE THREAD

**Issue by a15355447898a** [Richasy/ReaderCopilot.Public#2]
在"rss追踪"中,可以通过授权"rss追踪"来同步inoreader
但是在"阅读助理"中只能通过api来同步了,而inoreader的api是需要购买pro服务才拥有的,这对于免费用户并不友好
请添加回来

**Comment by Richasy** [comment]
你好，我明天你的诉求，但是 inoreader 这边更新了他们的授权流程，仅向付费用户开放 API 数据交互。

RSS 追踪能够通过 OAuth 的方式去做到这一点，是因为当时（两年前），还允许免费注册，但现在已经不行了。

我不能保证 RSS 追踪的客户端 id 会在何时取消，所以目前我只能让用户自行填写相关的 client id。

在未来等到阅读助理具备了足够多的用户，我才有资格去联系 inoreader，协商合作事宜。

望理解。

---

但作为临时方案，inoreader提供了 PRO 试用，虽然时间不长，但是你可以在此期间注册一个客户端，并在之后持续使用

**Comment by Richasy** [comment]
下次更新安排，但需要你退出登录并重新连接

**Comment by Richasy** [comment]
此问题已修复，请更新至新版本（1.2310.2.0）
