### ISSUE TITLE
[Feature Request] 请求加回此前 RSS Tracker 对 Feedly 的支持

### ISSUE THREAD

**Issue by ericclose** [Richasy/ReaderCopilot.Public#20]
需求：希望加回此前 RSS Tracker 对 Feedly 的支持，that's all.

**Comment by Richasy** [comment]
Feedly 对于 API 的限制很严格，即便应用提供支持，也只能提供很有限的操作，而且你每个月都要更换 Developer Token，这个感觉用户体验挺差的，所以不是当前的优先事项
