### ISSUE TITLE
同播客订阅地址RSS追踪正常使用，阅读助理提示不支持解析该源

### ISSUE THREAD

**Issue by zirui0504** [Richasy/ReaderCopilot.Public#22]
同播客订阅地址RSS追踪正常使用，阅读助理提示不支持解析该源
链接地址为https://data.getpodcast.xyz/data/lizhi/1372342.xml
RSS追踪用的是OneDrive，阅读助理用的是本地RSS

**Comment by Richasy** [comment]
没有复现这个问题，另外如果是播客的话，为什么不使用阅读助理的播客功能进行管理呢？

**Comment by zirui0504** [comment]
> 没有复现这个问题，如果另外是播客的话，为什么不使用阅读助手的播客功能进行管理呢？

抱歉这么久没有看，因为有些是蜻蜓、荔枝、网易云的节目，在阅读助手的博客源里是没有的；
这个问题是订阅是可以正常订阅的，但选择节目进行播放的时候会提示不支持解析该源
![image](https://github.com/Richasy/ReaderCopilot.Public/assets/40077625/9a57c027-8664-44a6-a3d8-0b9d59616bb7)

**Comment by Richasy** [comment]
哦哦，了解了，看了一下播客源，问题在于该播客源是第三方工具生成的（audio.getpodcast.xyz），音频播放地址需要二次跳转，而播放器不支持链接跳转。
这个我额外适配一下吧

**Comment by lisansas** [comment]
> 已经在 1.2312.3.0 中修了，在听之前你可以先右键播客条目，选择`清除本地缓存`，把旧数据刷掉，应该就可以了

我也找到一个

![图片](https://github.com/Richasy/ReaderCopilot.Public/assets/38862056/e58dc7f7-133b-448e-83a8-7e9b0e1302b8)
https://feeds.buzzsprout.com/981940.rss
