### ISSUE TITLE
[新功能请求]希望加入夜间模式一键切换

### ISSUE THREAD

**Issue by hsake233** [Richasy/ReaderCopilot.Public#24]
晚上还得手动切换背景与字体颜色，属实麻烦，希望能有多个预设一键切换

**Comment by Richasy** [comment]
你指的是 epub 阅读吗？

**Comment by hsake233** [comment]
> 你指的是 epub 阅读吗？

无论是txt还是epub格式我都没有找到快速切换夜间白天的选项🥺

**Comment by Richasy** [comment]
新的版本（v2.2412.13.0）提供了一个自定义主题的切换按钮，这两天就会过审发布，届时可以更新一下看看
