### ISSUE TITLE
[Bug]inoreader无法完成授权步骤

### ISSUE THREAD

**Issue by xianzheTM** [Richasy/ReaderCopilot.Public#25]
![image](https://github.com/Richasy/ReaderCopilot.Public/assets/25103583/5bb5151b-fef4-4249-805d-c54f821863f0)
点击打开阅读助理后出现阅读助理APP，然后没有任何反应了。
尝试使用RSS追踪重新授权能正常授权。在别的页面通过浏览器打开其他的APP没有问题。

**Comment by Richasy** [comment]
1.2311.1.0 修复了这个问题，预计明天可以通过审核并更新
