### ISSUE TITLE
能否实现rss追踪三列的视图

### ISSUE THREAD

**Issue by lxmwwl** [Richasy/ReaderCopilot.Public#27]
希望能够实现rss追踪三列的视图，订阅源一个区域、订阅源文章一个区域，具体文章内容一个区域，点击文章再打开一个页面的交互方式还是没有原本rss追踪的好用

**Comment by Richasy** [comment]
目前 UI 已经进行了重新设计，但是三列的设计对于平板并不友好，独立窗口阅读更具备通用性。
