### ISSUE TITLE
能否依然保留原rss上播放音频的功能

### ISSUE THREAD

**Issue by lxmwwl** [Richasy/ReaderCopilot.Public#28]
用来播放一些播客，没有专门选择播客软件听，一方面是为了方便多端同步，还有就是没有那么多时间rss和播客兼顾，所以只用rss听少量喜欢的播客

**Comment by Richasy** [comment]
这个目前并不在计划内，既然应用提供了专门的播客模块，那么让两个模块彼此交叉可能并不是一个好的设计思路
