### ISSUE TITLE
初始化语音模块，尝试连接到小幻助理失败AppUnavaible

### ISSUE THREAD

**Issue by Looong01** [Richasy/ReaderCopilot.Public#29]
使用阅读助理的朗读功能，初始化语音模块时，显示尝试连接到小幻助理失败AppUnavaible，如图：

![image](https://github.com/Richasy/ReaderCopilot.Public/assets/69568351/84a3cbcf-530a-4423-85f1-818e50358006)

阅读助理和小幻助理均为微软商店版

小幻助理已配置好Azure语音服务，并成功运行，如图：

![image](https://github.com/Richasy/ReaderCopilot.Public/assets/69568351/18ceea8f-b6ea-4591-a0a9-efe3dbb0aa0b)

**Comment by Richasy** [comment]
这个功能目前还存在一些问题，需要重新设计，届时会和新的小幻助理一起发布

**Comment by Richasy** [comment]
该功能目前已经不再需要连接小幻助理，可以在应用内单独配置
