### ISSUE TITLE
[Bug]本地epub图书无法导入

### ISSUE THREAD

**Issue by PIut02** [Richasy/ReaderCopilot.Public#3]
虽然查看阅读库中已经导入，但在书架中无法显示，重新导入提示重复文件，在干净阅读中没有此问题
log如下：
[applog.2023-09-29.log](https://github.com/Richasy/ReaderCopilot.Public/files/12768623/applog.2023-09-29.log)

**Comment by Richasy** [comment]
可以将 epub 发送到我的邮箱：thansy@foxmail.com 吗？这边看上去是文件属性缺失，我需要确定具体的属性以便修复这个问题

**Comment by PIut02** [comment]
已经发邮箱了

**Comment by Richasy** [comment]
收到，目前国庆期间我可能没有时间看这个问题，在休假结束后会尽快处理

**Comment by Richasy** [comment]
此问题已修复，请更新至新版本（1.2310.2.0）
