### ISSUE TITLE
pdf文件名字中有日期时排序不正确

### ISSUE THREAD

**Issue by AIKA1024** [Richasy/ReaderCopilot.Public#30]
xxxx-11.3号和xxxx-11.28号，11.28号会在11.3号前面，并且现在文件名较长时，名字后面会被省略，要鼠标放上去才看得到全名，这个问题和排序错乱的问题和在一起，找书会很困难
![image](https://github.com/Richasy/ReaderCopilot.Public/assets/68951745/03c499ea-1857-42fd-9723-3ee786ebc622)

**Comment by Richasy** [comment]
我会在近期调研这个问题，以寻找一个解决办法

**Comment by Richasy** [comment]
如果单就你当前的命名规则来说，可以处理。但是考虑到其它五花八门的命名，通用性不强。目前最好的方法还是在用户侧修改文件名，比如11.3改为11.03，以这种双位数命名可以避免排序歧义。
