### ISSUE TITLE
[新功能请求]能否增加一个rss阅读内视频自动选择播放的选项

### ISSUE THREAD

**Issue by glassywater** [Richasy/ReaderCopilot.Public#31]
![image](https://github.com/Richasy/ReaderCopilot.Public/assets/42326344/647e8f70-94f3-4604-8ac0-0be837b35fb3)
有些rss内容里面的视频都是很短时间的视频，一个个拿鼠标去点，很影响阅读体验

**Comment by Richasy** [comment]
视频自动播放并不是一种很好的体验，如果视频在文章的末尾，可能会导致用户感到疑惑（哪儿来的声音）。如果说做成滚动到视区内再自动播放，这个并不在规划内，我还是希望 RSS 阅读能保持干净和默认，尽可能降低额外的网络请求
