### ISSUE TITLE
关于RSS订阅一直报错的问题

### ISSUE THREAD

**Issue by wfyihai** [Richasy/ReaderCopilot.Public#33]
如下图，每次打开RSS都报错，但又不知道哪里出错了，另外就是不知道从哪里导入RSS的订阅文件了。之前导过一次，后面不记得在哪能导了。向下面图片中这种错误真的让使用者很茫然，能否给出错误原因或出现错误后有一个引导性的解决方案呢？
![image](https://github.com/Richasy/ReaderCopilot.Public/assets/3362338/594e68ad-9d96-472c-8659-3f6c13b63cf0)

**Comment by Richasy** [comment]
抱歉带给你不好的体验，这是一些可能有用的解决办法：

## 查看错误详细信息日志

进入应用设置页面，找到日志记录区块，打开日志文件夹，找到当日的日志记录进行查看。也可以把该日志文件发送到这个issue线程，以便我定位问题出处。

## 如何解决问题

出现这个情况，很可能是因为内部数据解析出现异常。如果你还有opml文件，可以打开你的阅读库，进入 `RssCache` 目录，删除 `Local` 文件夹。

然后重启应用，这时就可以重新导入 OPML 进行同步了

**Comment by Richasy** [comment]
暂时关闭此问题，因为没有进一步的更新
