### ISSUE TITLE
[新功能请求]划词菜单希望增加能让选定句子收藏+划色

### ISSUE THREAD

**Issue by lisansas** [Richasy/ReaderCopilot.Public#34]
如题，作为一款阅读软件没有这两个功能我觉得十分别扭。

干净阅读的时候还可以管理笔记，对我个人来说这属于刚需功能了。

感谢。

**Comment by Richasy** [comment]
我还在思考该功能具体该如何实现，是否需要接入外部服务，但短期内，应该不是优先考虑事项

**Comment by Richasy** [comment]
内测版本已经实现语句高亮/批注，如果还没有进群，请加入 858688642 并申请内测
