### ISSUE TITLE
安卓阅读书源加载失败

### ISSUE THREAD

**Issue by Onlyasdf** [Richasy/ReaderCopilot.Public#35]
提示是 response status code dose not indicate success：500
<img width="716" alt="1" src="https://github.com/Richasy/ReaderCopilot.Public/assets/32995492/f56b766c-0dbf-4bcc-9016-4e80e1ff4ce0">

**Comment by fenraoA** [comment]
我也是相同的问题，有什么解决的方法吗

**Comment by Richasy** [comment]
确认以下几件事：

1. 打开 `终端` 或者 PowerShell，输入命令 `dotnet --version`，查看 .NET 版本是否为 8.0 以上，如果不是，先尝试安装 [.NET8 运行时](https://dotnet.microsoft.com/zh-cn/download/dotnet/thank-you/runtime-desktop-8.0.0-windows-x64-installer).
2. 如果 .NET 版本没问题，请确认你的阅读服务是可以被访问的。比如你在手机上打开了阅读的 `Web 服务`，请在浏览器中输入对应的网址，查看是否可以打开网页。如果打不开，这表示你的电脑网络可能和手机网络不在同一网络下，请自行解决。
3. 如果你可以在网页上打开阅读服务地址，那么请尝试这个 API 地址是否可以访问：`http://你的服务地址/getBookshelf`，如果你能看到内容，嗯……那可能确实是应用的问题，但是目前尚不清楚原因。你可以试着从应用商店下载我的另一款应用：网络回环管理器，在里面勾选 `阅读助理` 并保存，然后重启应用进行尝试

**Comment by fenraoA** [comment]
> 确认以下几件事：
> 
> 1. 打开 `终端` 或者 PowerShell，输入命令 `dotnet --version`，查看 .NET 版本是否为 8.0 以上，如果不是，先尝试安装 [.NET8 运行时](https://dotnet.microsoft.com/zh-cn/download/dotnet/thank-you/runtime-desktop-8.0.0-windows-x64-installer).
> 2. 如果 .NET 版本没问题，请确认你的阅读服务是可以被访问的。比如你在手机上打开了阅读的 `Web 服务`，请在浏览器中输入对应的网址，查看是否可以打开网页。如果打不开，这表示你的电脑网络可能和手机网络不在同一网络下，请自行解决。
> 3. 如果你可以在网页上打开阅读服务地址，那么请尝试这个 API 地址是否可以访问：`http://你的服务地址/getBookshelf`，如果你能看到内容，嗯……那可能确实是应用的问题，但是目前尚不清楚原因。你可以试着从应用商店下载我的另一款应用：网络回环管理器，在里面勾选 `阅读助理` 并保存，然后重启应用进行尝试

看了一下，自己是.net6.0的，按照8.0然后重启之后还是应用无法访问，浏览器可以。然后也试过了网络回环管理器，勾上之后还是同样应用无法访问

**Comment by fenraoA** [comment]
> 确认以下几件事：
> 
> 1. 打开 `终端` 或者 PowerShell，输入命令 `dotnet --version`，查看 .NET 版本是否为 8.0 以上，如果不是，先尝试安装 [.NET8 运行时](https://dotnet.microsoft.com/zh-cn/download/dotnet/thank-you/runtime-desktop-8.0.0-windows-x64-installer).
> 2. 如果 .NET 版本没问题，请确认你的阅读服务是可以被访问的。比如你在手机上打开了阅读的 `Web 服务`，请在浏览器中输入对应的网址，查看是否可以打开网页。如果打不开，这表示你的电脑网络可能和手机网络不在同一网络下，请自行解决。
> 3. 如果你可以在网页上打开阅读服务地址，那么请尝试这个 API 地址是否可以访问：`http://你的服务地址/getBookshelf`，如果你能看到内容，嗯……那可能确实是应用的问题，但是目前尚不清楚原因。你可以试着从应用商店下载我的另一款应用：网络回环管理器，在里面勾选 `阅读助理` 并保存，然后重启应用进行尝试

http://你的服务地址/getBookshelf    这个网址在浏览器中也能正确的获取到内容。。。顺便一提，我更新到最新版本了  然后语音配置好了也不能使用，地区设置的eastus 和 East US 都试过，在安卓上面的TTS server这个软件已经成功配置过一次了所以应该不是我的问题。我感觉可能和软件是否能够成功通过代理访问网络有关系，我个人是通过路由器安装clash弄的全设备访问的。可能软件弄个自定义代理的设置能够解决？

**Comment by Richasy** [comment]
我和你的环境是类似的，我这边是 OpenWrt + OpenClash。

语音不能正常使用是指的不能获取到声音列表，还是说不能转换成声音进行播放？如果报错了，可以在设置里找到日志记录，打开当天的日志记录发到这个线程上，我看能不能确认问题的原因。

阅读书源的问题，我想和你确认一下，就是你的书架列表里是否包含了非文本小说，比如有声小说或者漫画？

**Comment by fenraoA** [comment]
> 我和你的环境是类似的，我这边是 OpenWrt + OpenClash。
> 
> 语音不能正常使用是指的不能获取到声音列表，还是说不能转换成声音进行播放？如果报错了，可以在设置里找到日志记录，打开当天的日志记录发到这个线程上，我看能不能确认问题的原因。
> 
> 阅读书源的问题，我想和你确认一下，就是你的书架列表里是否包含了非文本小说，比如有声小说或者漫画？

[语音是已经能选择语言和声音，但是点播放就尝试播放段落失败重新生成]
<img width="261" alt="PixPin_2024-01-02_12-35-15" src="https://github.com/Richasy/ReaderCopilot.Public/assets/80891246/61fbf8d7-980d-4ef3-8922-c3fe8cd71f11">

阅读书源的话，书架里是没有非文本小说的，但是数量有点多，大概有300本

这是日志记录
[applog.2024-01-02.log](https://github.com/Richasy/ReaderCopilot.Public/files/13807154/applog.2024-01-02.log)

**Comment by Onlyasdf** [comment]
> 确认以下几件事：
> 
> 1. 打开  或者 PowerShell，输入命令 ，查看 .NET 版本是否为 8.0 以上，如果不是，先尝试安装 [. NET8 运行时](https://dotnet.microsoft.com/zh-cn/download/dotnet/thank-you/runtime-desktop-8.0.0-windows-x64-installer).`终端``dotnet --version`
> 2. 如果 .NET 版本没问题，请确认你的阅读服务是可以被访问的。 比如你在手机上打开了阅读的 ，请在浏览器中输入对应的网址，查看是否可以打开网页。 如果打不开，这表示你的电脑网络可能和手机网络不在同一网络下，请自行解决。`Web 服务`
> 3. 如果你可以在网页上打开阅读服务地址，那么请尝试这个 API 地址是否可以访问：，如果你能看到内容，嗯…… 那可能确实是应用的问题，但是目前尚不清楚原因。 你可以试着从应用商店下载我的另一款应用：网络回环管理器，在里面勾选  并保存，然后重启应用进行尝试`http://你的服务地址/getBookshelf``阅读助理`

以上步骤都试过了，还是没用

**Comment by Richasy** [comment]
有一个大概的猜测，可以试下新发布的阅读插件：https://github.com/Richasy/ReaderCopilot.Public/releases/tag/1.2401.2.0

**Comment by fenraoA** [comment]
> 有一个大概的猜测，可以试下新发布的阅读插件（选择适用自己设备的架构平台）：https://github.com/Richasy/ReaderCopilot.Public/releases/tag/1.2401.2.0

已试，还是一样

**Comment by Richasy** [comment]
这个问题有点诡异，加个群吧：858688642

**Comment by Onlyasdf** [comment]
> 有一个大概的猜测，可以试下新发布的阅读插件（选择适用自己设备的架构平台）：https://github.com/Richasy/ReaderCopilot.Public/releases/tag/1.2401.2.0

的确，换了还是没用

**Comment by Richasy** [comment]
找到问题原因了，请下载最新的插件以进行修复
