### ISSUE TITLE
导入书籍无法显示，导入插件无法使用

### ISSUE THREAD

**Issue by MarChieX** [Richasy/ReaderCopilot.Public#37]
书籍已复制到阅读库，设置中可显示书源插件。
[applog.2024-01-01.log](https://github.com/Richasy/ReaderCopilot.Public/files/13802150/applog.2024-01-01.log)

**Comment by MarChieX** [comment]
半解决：将应用移动至C盘。
复现：将应用安装至非系统盘。

**Comment by Richasy** [comment]
目前非系统盘安装可能存在一些问题，应该是由于框架或者系统自动加密导致的。目前在应用侧可能不太好修。

关联问题：#36
