### ISSUE TITLE
书源问题

### ISSUE THREAD

**Issue by jopkyb** [Richasy/ReaderCopilot.Public#38]
计算机小白，书源上网上搜了搜大部分都是json格式的，有别的办法导入吗？

**Comment by Richasy** [comment]
看下：https://readercopilot.richasy.com/docs/book-source

**Comment by jopkyb** [comment]
懂了，网文的话需要每天更新，所以用这个，文档里面的那个地址足够了。出版的书的话要自己下载。
还有个问题，1.有的书显示不了封面2.一次下滑太多行了，直接显示到下面了，有一部分读不到
________________________________
发件人: ***@***.*** ***@***.***> 代表 Richasy ***@***.***>
发送时间: 2024年1月3日 01:38
收件人: Richasy/ReaderCopilot.Public ***@***.***>
抄送: jopkyb ***@***.***>; Author ***@***.***>
主题: Re: [Richasy/ReaderCopilot.Public] 书源问题 (Issue #38)


看下：https://readercopilot.richasy.com/docs/book-source

―
