### ISSUE TITLE
RSS订阅文章内容解析错误

### ISSUE THREAD

**Issue by CharacterM** [Richasy/ReaderCopilot.Public#43]
订阅网址为https://blog.codingnow.com/atom.xml
助理内显示如附图。
![pic1](https://github.com/Richasy/ReaderCopilot.Public/assets/129607249/9576b933-7bae-44b0-9bc7-41a61b57ecc5)
下了个fluent reader试了试是正常的。

**Comment by Richasy** [comment]
新的版本（v2.2412.13.0）修复了这个问题，这两天就会过审发布，届时可以更新一下看看
