### ISSUE TITLE
[BUG]OpenAI使用代理时，书童提问还是走OpenAI官方

### ISSUE THREAD

**Issue by cliouo** [Richasy/ReaderCopilot.Public#45]
# Describe the bug
1. OpenAI使用代理时，书童提问还是走OpenAI官方API，因此报错。
导入文档后的索引是正常走代理点的，就只有提问出问题。
2. 其他小问题:
OpenAI内核配置时，只有重启程序才会重新调用/v1/models接口刷新可用模型
阅读书籍时缺少输入跳转指定页码的功能
# Platform
Windows11

# Software Version
1.2401.4.0

# Log
![image](https://github.com/Richasy/ReaderCopilot.Public/assets/71540889/5db227c9-c922-40f5-be90-5a5519ae4d23)

![image](https://github.com/Richasy/ReaderCopilot.Public/assets/71540889/bd442739-f09c-4de7-860e-25e03ae04afe)

**Comment by Richasy** [comment]
新版本暂时移除了 RAG 支持（目前该功能还有待进一步完善），我正在重写底层库以满足自定义需求。
暂时关闭这个问题
