### ISSUE TITLE
无法使用服务器版阅读，错误码是500

### ISSUE THREAD

**Issue by xuangeyouneihan** [Richasy/ReaderCopilot.Public#53]
我已经去开发者模式里获取了token，格式确认是`[用户名]:[Token]`。服务器是甲骨文云的免费AMD机器，在开放所有端口所有流量所有协议后仍出现此问题。阅读版本是`3.2.7-01010833`。我怀疑是因为我没有注册域名，我填写的网站是`http://[IP地址]:[端口]`。无论怎么刷新都报500

**Comment by Richasy** [comment]
新的版本（v2.2412.13.0）也许可以解决这个问题，这两天就会过审发布，届时可以更新一下看看
