### ISSUE TITLE
能否添加对Webdav的支持？

### ISSUE THREAD

**Issue by Meonthb** [Richasy/ReaderCopilot.Public#55]
希望能实现IOS和Windows的EPUB电子书同步，目前为止没有一款跨平台阅读软件能比较好的实现同步，不过如果能支持Webdav的话就可以通过网盘来实现同步。

**Comment by Richasy** [comment]
内测版本已经实现从 WebDAV 导入书籍，如果还没有进群，请加入 858688642 并申请内测
