### ISSUE TITLE
番茄书源打开后Internal server error

### ISSUE THREAD

**Issue by Looong01** [Richasy/ReaderCopilot.Public#58]
![image](https://github.com/Richasy/ReaderCopilot.Public/assets/69568351/b678ddb9-8728-4605-84a5-3ba1d5a36de6)

番茄书源打开后Internal server error，其他书源的没问题

**Comment by Richasy** [comment]
由于番茄经常封 API，所以书源很不稳定，新的版本将不再提供支持
