### ISSUE TITLE
打开阅读文件窗口后取消分屏，无法恢复正常查看

### ISSUE THREAD

**Issue by maxwellwhy** [Richasy/ReaderCopilot.Public#59]
在扩展屏下打开文档进行查看时，若取消扩展屏幕，文件窗口此时若处于右侧，则会出现无法找到文档窗口的问题

**Comment by Richasy** [comment]
在新版本中，我无法复现该问题，不论是在设置中禁用某个屏幕的显示，或者突然拔掉某个屏幕的接口，阅读窗口都可以正确切换到另一个屏幕上。
我先关闭这个问题，如果这个问题依然能在新版本上复现，可以再open它，并提供应用日志等可能有帮助的内容
