### ISSUE TITLE
插件初始化失败

### ISSUE THREAD

**Issue by Pengyou0926** [Richasy/ReaderCopilot.Public#61]
尝试启动插件服务失败,请检查插件有效性后重试

<img width="644" alt="PixPin_2024-07-29_21-02-43" src="https://github.com/user-attachments/assets/84fa0fcd-99d9-46fe-b57c-8fc515426f11">

**Comment by Richasy** [comment]
由于目前的书源极不稳定，新的版本将不再提供内置插件的支持，以本地阅读优先，但可以连接阅读或者阅读服务器
