### ISSUE TITLE
番茄没办法用

### ISSUE THREAD

**Issue by mengtiankf** [Richasy/ReaderCopilot.Public#63]
![PixPin_2024-10-09_02-17-07](https://github.com/user-attachments/assets/5f2dbaf2-e909-4e80-b395-c207590d96bb)

**Comment by Richasy** [comment]
番茄的API在频繁更新，目前已经很难获取到章节内容，建议优先使用安卓阅读里的书源，再导入到阅读助理中。

下个版本也不再提供对番茄的内置支持

**Comment by mengtiankf** [comment]
@Richasy 大佬，在播客界面可以增加一个点击时间可以跳转的功能吗？
