### ISSUE TITLE
十分钟体验，简单提点建议

### ISSUE THREAD

**Issue by Viel0320** [Richasy/ReaderCopilot.Public#71]
看到群里有内测，加上打折就买了，十分钟体验，简单提点建议，可能语气并未十分恭敬，见谅

以下为正文，基于~~1.2406.1.0~~ 2.2411.1.0：

书架：
~~1 封面应为正方或长方，如果一定要保留正方，用户应可以选择为长方（当然现在既不是长方也不是完全正方）
2 单个文件应当限制打开一个窗口，最好在打开时有过渡动画拦截操作，防止用户重复打开~~

3 书架窗口应支持拖入文件添加

epub阅读器：
~~1 非全屏模式操作栏最好不要隐藏吧，否则操作逻辑非常奇怪，而且拖动窗口和打开目录等常规操作都很繁琐迷惑（其实全屏也不需要隐藏）~~
~~2 edge tts似乎无法调用~~

3 字体选择最好允许搜索，自定义字体应当增加强制全局覆盖的选项（并且给与一定的警告，因为可能会导致样式问题）

~~4 书籍内注释跳转一定要做成预览形式，而不要直接跳，可以打开一个窗口预览，当然最好还是能像calibre自带阅读器一样全部转换为弹注（此条个人认为最重要）~~

~~书源插件：
1 导入后应当允许删除，最好可以按条删除或按包，现在即便手动删除插件文件依旧会展示选项，需要自己改配置~~

播客&播客源：
1 播客源应当作为播客的下级页面（或者说下级入口）
2 播客源地区不应恒定采用系统地区，应当默认采用系统地区，但允许手动配置
~~3 播客播放时，操作栏的播放列表入口页面，可以展示更新时间~~

~~4 播客和rss都应当允许opml标准文件导入~~

全局：
1 希望允许用户隐藏不需要的功能入口（鉴于内测实际只有三个功能，降级）
2 关闭窗口时的不要再询问我选项不应总是勾选，应当首次勾选，后续保留为上次

**Comment by Richasy** [comment]
播客源的地区设置准备依然保持现状，我并不想自己维护一套地区设置，遵循当前的系统设置是个更符合设计规范的选择
