### ISSUE TITLE
[Bug] B站订阅更新Bug

### ISSUE THREAD

**Issue by hizuhi** [Richasy/ReaderCopilot.Public#79]
### Bug 描述 / Description

当更新哔哩哔哩订阅，或点击关注up主头像时会出现如下错误：
`Call failed. The SSL connection could not be established, see inner exception: POST https://grpc.biliapi.net/bilibili.app.dynamic.v2.Dynamic/DynVideoPersonal`

### 复现问题的步骤 / Steps to reproduce

```plain text
如上
```

### 预期行为 / Expected behavior

应该会获取当前UP主的主页内容

### 截图 / Screenshots

![bili_bug](https://github.com/user-attachments/assets/74dc6b8a-083c-4c9d-91bf-81912bb12214)

### 系统版本

- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [X] Windows 11 23H2 (Build 22631)
- [ ] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明) / Other (Specify)

### 运行设备 / Running device

桌面（个人电脑） / Desktop (Personal Computer)

**Comment by Richasy** [comment]
你是不是开了广告屏蔽插件（比如Ad guard）？在规则里去掉对 grpc.biliapi.net 的屏蔽即可

**Comment by hizuhi** [comment]
感谢！是因为走了v2ray代理，添加一个规则走直连就可以了
