### ISSUE TITLE
[Bug] 竪排時的觸控滑動翻頁方向問題

### ISSUE THREAD

**Issue by larachung** [Richasy/ReaderCopilot.Public#80]
### Bug 描述 / Description

1. 在竪排 epub 書籍中，使用觸屏滑動翻頁時，翻頁動作會變成不符合通常使用邏輯的上下滑動。而且部分竪排 epub 可能會有目錄、出版信息等橫排部分，此時翻頁方向又使用橫排翻頁的方式，使一本書中同時出現兩種翻頁向，更加不符合邏輯。方向鍵翻頁無此問題；
2. 竪排中的橫排部分的分頁也會變成橫排書籍的從左向右，而非和全書保持一致。

### 复现问题的步骤 / Steps to reproduce

```plain text
打開竪排書籍既可。
```

### 预期行为 / Expected behavior

1. 調整觸屏滑動翻頁，使其在竪排時和方向鍵翻頁一樣合乎邏輯，特別是且令竪排書中的橫排部分的翻頁行為與全書保持一致；
2. 豎排（即從右向左閲讀）書籍中的橫排部分閲讀方向應與整本書保持一致。即在epub文件中，翻頁的閲讀方向應通過epub中的opf文件內的`<spine page-progression-direction="rtl">`來設置（其中rtl表示從右向左閲讀，ltr表示從左向右閲讀，默認為ltr）。

### 系统版本

- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [X] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明) / Other (Specify)

### 运行设备 / Running device

ARM64 设备 / ARM64 Device

**Comment by Richasy** [comment]
在 2.2412.18.0 中修復，預計明日推送

**Comment by larachung** [comment]
> 在 2.2412.18.0 中修復，預計明日推送

感謝，但問題仍未完全解決，以下是樣例文件，可以看到：
1. 竪排部分觸控翻頁方向已修復正常，但缺少動畫；
2. 封面、扉頁、插圖、版權頁等橫排部分依舊套用橫排書籍翻頁邏輯，使得同一本書內時而左翻時而右翻；
3. 「2.」中提到的部分在超出一頁時（如縮小視窗，使本書的版權頁分為兩頁）除上述翻頁邏輯外，分頁邏輯也錯誤套用了橫排書籍，如竪排書籍中的第 n 與 n + 1 頁為橫排，理應第 n 頁在右，第 n + 1 頁在左，而非現在的反之，在存在兩頁以上橫排頁，如注釋頁的書籍中，現行顯示效果會非常奇怪。

[印刷書頁碼範本.zip（請將擴展名改為epub後打開）](https://github.com/user-attachments/files/18240582/default.zip)

**Comment by Richasy** [comment]
2.2412.19.0 进行了一些修复，现在会保持滚动方向一致。
但是不支持滚动动画，因为实际的排版依然是上下排列
