### ISSUE TITLE
[Bug] 导入小说后打开报错

### ISSUE THREAD

**Issue by akschy** [Richasy/ReaderCopilot.Public#81]
### Bug 描述 / Description

本地小说导入后打开会报错
![image](https://github.com/user-attachments/assets/22e952a9-608a-409c-a91a-257957c4a075)

### 复现问题的步骤 / Steps to reproduce

```plain text
导入书籍 然后打开书籍
```

### 预期行为 / Expected behavior

正常阅读

### 截图 / Screenshots

![image](https://github.com/user-attachments/assets/22e952a9-608a-409c-a91a-257957c4a075)

### 系统版本

- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [X] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明) / Other (Specify)

### 运行设备 / Running device

桌面（平板或笔记本） / Desktop (Tablet or Laptop)

**Comment by Richasy** [comment]
你是导入的 txt 书籍拆分章节后出现的吗？

**Comment by Richasy** [comment]
会在 2.2412.20.0 中修复，作为临时解决方案，你可以去掉 txt 文件名里的标点符号后重新导入
