### ISSUE TITLE
[Bug] 添加BazQux Reader为Google Reader订阅源时无法拉取文章列表

### ISSUE THREAD

**Issue by ZEROIC** [Richasy/ReaderCopilot.Public#83]
### Bug 描述 / Description

添加BazQux Reader为RSS订阅源(使用Google Reader Api)，无法拉取文章列表并弹出英文错误提示。

### 复现问题的步骤 / Steps to reproduce

```plain text
RSS中连接服务Google Reader，服务器填写https://bazqux.com，认证成功后可触发。
```

### 预期行为 / Expected behavior

弹出错误提示，文章列表也为空。偶尔可以在左侧看到订阅源列表，该列表与线上服务一致，但展开后没有文章。

### 截图 / Screenshots

![QQ20241231-130935](https://github.com/user-attachments/assets/67a7a893-d168-4e2e-90dc-c4e6bf06ab94)
![QQ20241231-131107](https://github.com/user-attachments/assets/38cf03d9-af85-4c5f-adda-e06f7e08a3eb)

### 系统版本

- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Windows 11 22H2 (Build 22621)
- [ ] Windows 11 23H2 (Build 22631)
- [X] Windows 11 24H2 (Build 26100)
- [ ] 其它 (需注明) / Other (Specify)

### 运行设备 / Running device

桌面（个人电脑） / Desktop (Personal Computer)

### 日志记录 / Log

[log-2024-12-31.txt](https://github.com/user-attachments/files/18279395/log-2024-12-31.txt)

### 备注 / Additional context

[BazQux Reader对于Google Reader Api的说明](https://github.com/bazqux/bazqux-api)

**Comment by Richasy** [comment]
会在 2.2412.22.0 中修复，今天晚些时候会推送
