### ISSUE TITLE
书源插件无法启用

### ISSUE THREAD

**Issue by AzusaYukina** [Richasy/ReaderCopilot.Public#9]
依照教程加载插件后切换到插件，无法使用
![image](https://github.com/Richasy/ReaderCopilot.Public/assets/53286112/8f166272-0a1b-4d74-9b1a-29bdf6f38456)
![image](https://github.com/Richasy/ReaderCopilot.Public/assets/53286112/f748762c-ea71-4c76-b443-43ace1c4b22f)

**Comment by Richasy** [comment]
两种解决方案：

1. 下载 [.NET SDK](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-7.0.401-windows-x64-installer) 并安装，然后重启设备，打开应用即可使用。
2. 我上传了一个新的插件文件 [book-source-plugin-dotnet](https://github.com/Richasy/ReaderCopilot.Public/releases/download/1.2309.1.0/book-source-plugin-dotnet.rcpkg)，你可以下载后重新导入该插件（如果出现导入失败，那么再导入一次）。这个方法不用下载 .NET SDK，但是插件包会大一些。

---

我晚些时候更新文档
